### ISSUE TITLE
color modifications of cars

### ISSUE THREAD

**Issue by YugalPradhan** [YugalPradhan/car#2]
All enemy cars have same color , modify game so that different cars have different color

**Comment by VidishaAG** [comment]
Can i be assigned please? I want to work on this

**Comment by YugalPradhan** [comment]
@VidishaAG  sure , go ahead

**Comment by VidishaAG** [comment]
@YugalPradhan please add the correct label for hacktoberfest. It is hacktoberfest and not hactoberfest.
