### ISSUE TITLE
Modifications required when starting the game

### ISSUE THREAD

**Issue by YugalPradhan** [YugalPradhan/car#3]
When we start the game different pc sizes have different UI's , that doesn't look good
When we start game the position of cars is such that game gets over just by starting the game, modify the starting positions of cars so that we get enough time to get started.

**Comment by Rutwik187** [comment]
hi. Can you please assign this to me. I have a good hand on JavaScript

**Comment by YugalPradhan** [comment]
go ahead @Rutwik187
