### ISSUE TITLE
Folder structure needs improvement

### ISSUE THREAD

**Issue by NiteshTiwari2002** [YugalPradhan/car#5]
The folder structure isn't organized. The assets like images, mp3s should have a different folder. This will make the repo look clean

I want to work on this issue. Please assign it to me with HACKTOBERFEST tag.

<img src="https://user-images.githubusercontent.com/109803142/194722058-781a45ee-c8af-44ba-b4ad-46352d5dd7c5.png" width=400>

**Comment by YugalPradhan** [comment]
@NiteshTiwari2002  go ahead
